# Reference Alembic migration for RFC 0004: MCP Registry
# Generated by Claude Code
#
# This is a reference implementation. The actual migration will receive
# a generated revision ID and depend on the current head revision.

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mssql

revision = "PLACEHOLDER"
down_revision = "PLACEHOLDER"
branch_labels = None
depends_on = None


def _get_json_type():
    """Get appropriate JSON type for the current database."""
    dialect_name = op.get_bind().dialect.name
    if dialect_name == "mssql":
        return mssql.JSON
    else:
        return sa.JSON


def upgrade():
    json_type = _get_json_type()

    op.create_table(
        "mcp_servers",
        sa.Column("workspace", sa.String(63), nullable=False, server_default="default"),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("display_name", sa.String(256), nullable=True),
        sa.Column("description", sa.String(5000), nullable=True),
        sa.Column("update_mode", sa.String(20), nullable=False, server_default="manual"),
        sa.Column("latest_version_alias", sa.String(256), nullable=True),
        sa.Column("last_registered_version", sa.String(256), nullable=True),
        sa.Column("created_by", sa.String(256), nullable=True),
        sa.Column("last_updated_by", sa.String(256), nullable=True),
        sa.Column("creation_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("last_updated_timestamp", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("workspace", "name", name="mcp_servers_pk"),
    )

    op.create_table(
        "mcp_server_versions",
        sa.Column("workspace", sa.String(63), nullable=False, server_default="default"),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("version", sa.String(256), nullable=False),
        sa.Column("server_json", json_type, nullable=False),
        sa.Column("display_name", sa.String(256), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("source", sa.String(512), nullable=True),
        sa.Column("run_id", sa.String(32), nullable=True),
        sa.Column("runtime_metadata", json_type, nullable=True),
        sa.Column("is_deployed", sa.Boolean(), nullable=False, server_default=sa.false_()),
        sa.Column("created_by", sa.String(256), nullable=True),
        sa.Column("last_updated_by", sa.String(256), nullable=True),
        sa.Column("creation_timestamp", sa.BigInteger(), nullable=True),
        sa.Column("last_updated_timestamp", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("workspace", "name", "version", name="mcp_server_versions_pk"),
        sa.ForeignKeyConstraint(
            ["workspace", "name"],
            ["mcp_servers.workspace", "mcp_servers.name"],
            name="fk_mcp_server_versions_server",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )

    op.create_index(
        "ix_mcp_server_versions_is_deployed",
        "mcp_server_versions",
        ["workspace", "name", "is_deployed"],
    )

    op.create_table(
        "mcp_server_tags",
        sa.Column("workspace", sa.String(63), nullable=False, server_default="default"),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("key", sa.String(256), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("workspace", "name", "key", name="mcp_server_tags_pk"),
        sa.ForeignKeyConstraint(
            ["workspace", "name"],
            ["mcp_servers.workspace", "mcp_servers.name"],
            name="fk_mcp_server_tags_server",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "mcp_server_version_tags",
        sa.Column("workspace", sa.String(63), nullable=False, server_default="default"),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("version", sa.String(256), nullable=False),
        sa.Column("key", sa.String(256), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint(
            "workspace", "name", "version", "key", name="mcp_server_version_tags_pk"
        ),
        sa.ForeignKeyConstraint(
            ["workspace", "name", "version"],
            [
                "mcp_server_versions.workspace",
                "mcp_server_versions.name",
                "mcp_server_versions.version",
            ],
            name="fk_mcp_server_version_tags_version",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "mcp_server_aliases",
        sa.Column("workspace", sa.String(63), nullable=False, server_default="default"),
        sa.Column("name", sa.String(256), nullable=False),
        sa.Column("alias", sa.String(256), nullable=False),
        sa.Column("version", sa.String(256), nullable=False),
        sa.PrimaryKeyConstraint("workspace", "name", "alias", name="mcp_server_aliases_pk"),
        sa.ForeignKeyConstraint(
            ["workspace", "name"],
            ["mcp_servers.workspace", "mcp_servers.name"],
            name="fk_mcp_server_aliases_server",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )


def downgrade():
    op.drop_table("mcp_server_aliases")
    op.drop_table("mcp_server_version_tags")
    op.drop_table("mcp_server_tags")
    op.drop_index("ix_mcp_server_versions_is_deployed", table_name="mcp_server_versions")
    op.drop_table("mcp_server_versions")
    op.drop_table("mcp_servers")
